name: Custom Contribution
description: Propose a contribution that doesn't fit into the other categories
title: "[Custom]: "
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Custom Contribution Proposal
  - type: textarea
    id: description
    attributes:
      label: Contribution Description
      description: Describe what you want to contribute in detail.
    validations:
      required: true
  - type: textarea
    id: proposed_execution
    attributes:
      label: Proposed Execution
      description: How do you plan to execute this contribution?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ### More Information
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other relevant context here.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I confirm that I want to execute this contribution.
          required: true
        - label: I have searched the existing issues.
          required: true
